name: module_external_dependencies
description: Module with application dependencies
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:

  flutter_modular: ^5.0.2
  flutter_triple: 1.2.7+2
  mobx_triple: ^1.1.3+1
  firebase_auth: ^3.4.2
  dartz: ^0.10.1
  rive: ^0.9.0
  cloud_firestore: ^3.3.0
  curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.2.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.module_external_dependencies
    iosBundleIdentifier: com.example.moduleExternalDependencies
